apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: promote-run-
spec:
  params:
  - name: github-secret
    value: promote-secret
  - name: github-config
    value: promote-configmap
  - name: from
    value: "https://github.com/<OWNER>/<GITOPS-TEST-REPO>"
  - name: to
    value: "https://github.com/<OWNER>/<GITOPS-PROD-REPO>"
  - name: service
    value: service-a
  taskRef:
    name: promote
