language: go
go: 1.14
sudo: false
os: 
  - linux
  - osx
  # - windows (would be nice to have, ensure tests pass first before enabling!)

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.24.0
  
script:
  - $GOPATH/bin/golangci-lint run
  - go test ./...
  - go build -o services_$TRAVIS_OS_NAME ./cmd/services

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: services*
  skip_cleanup: true
  on:
    tags: true