cllanguage: go
go: 1.14
sudo: false

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.24.0

script:
  - $GOPATH/bin/golangci-lint run
  - go test ./...
  - go build ./cmd/services

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: promote
  on:
    tags: true