apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push
spec:
  workspaces:
  - name: repo
  resources:
    inputs:
      - name: git-source
        type: git
    outputs:
      - name: builtImage
        type: image
  params:
  - name: pathToDockerFile
    description: The path to the dockerfile to build
    default: ./repo/Dockerfile
  - name: commitId
    description: commit ID of the source
    default: v2
  - name: pathToContext
    description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
    default: ./repo
  steps:
  - name: build
    image: docker
    script: |
      #!/bin/sh
      cp -R git-source/. repo
      docker build -f $(params.pathToDockerFile) -t $(resources.outputs.builtImage.url) $(params.pathToContext)
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  - name: push 
    image: docker
    script: |
      #!/bin/sh
      docker tag $(resources.outputs.builtImage.url) $(resources.outputs.builtImage.url):$(params.commitId)
      docker push $(resources.outputs.builtImage.url):$(params.commitId)
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  - name: update 
    image: alpine
    script: |
      #!/bin/sh
      sed -i -e "s#\$IMAGE#\$(resources.outputs.builtImage.url):\$(params.commitId)#" $(params.pathToContext)/config/deploy.yaml
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket

