on:
  push:
    tags:
      - 'v*' # Push to a tag starting with a v

- name: Deploy Release
  stage: deploy
  os: linux
  script:
    - make VERSION=${TRAVIS_TAG}  package
    - make deploy

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release in progress!
          draft: false
          prerelease: false
